### ISSUE TITLE
Sign up and configure Github account

### ISSUE THREAD

**Issue by kbuzard** [kbuzard-SU/GATT-RAs#1]
Deadline: Monday, June 7 at 2pm
1. Go to GitHub's [Pricing](https://github.com/pricing) page.
2. Click "Join for Free" in the leftmost column.
3. Follow the prompts to create your personal account.
4. Follow [these instructions](https://docs.github.com/en/github/getting-started-with-github/signing-up-for-github/verifying-your-email-address) to verify your email account.
5. Decide whether to configure two-factor authentication; follow [these instructions](https://docs.github.com/en/github/authenticating-to-github/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication) if you wish to do so.
6. Personalize your profile if you wish using [these instructions](https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile).
7. Email Professor Buzard with your username so that she can add you to the repo.
8. After Professor Buzard adds you to the repo, you will receive an invitation to join the repo/team in your email. Accept the invitation.

Add a comment here when you have any questions as well as when you have completed all eight steps.
- Include how long it took you to complete the task.  Please include such a time estimate in your posts for each subsequent issue in the training sequence (we want to know how long these trainings take on average, and this is good practice in time tracking)
  - Experiment with systems that will work for you to track your time. I use [Clockify](https://clockify.me/), which not only tracks time flexibly but has a desktop app that helpfully records what applications I'm using and when I'm using them. This helps when I forget to start the timer, or get distracted and can't remember what I was doing for a given time interval
      - I find the [Pomodoro technique](https://www.themuse.com/advice/take-it-from-someone-who-hates-productivity-hacksthe-pomodoro-technique-actually-works) helps me to stay focused and track my time more easily. I don't follow it as rigidly as described in the linked article, but I *do* put my phone on silent and shut off desktop notifications to make sure I'm doing what I say I'm doing the whole time.
  - Once the substantive work has started, you will only have to enter the total for each day in your log, but it is sometimes useful to know how long particular tasks are taking so we can project future time requirements

When everyone has completed the task, I will *close* this issue. You'll be able to find it--and all other closed issues--by clicking on "Closed" in the list of issues.
- At this point, I will also make the repo *private* so that no one outside of our team can see it on the internet

**Comment by Kirs10-Riley** [comment]
I completed all 7 steps, it took 10 minutes.

**Comment by kbuzard** [comment]
> I completed all 7 steps, it took 10 minutes.

Great job! Thanks @Kirs10-Riley

**Comment by eldreddyl** [comment]
I have completed the 7 steps. It took me about 11 minutes.

**Comment by kbuzard** [comment]
> I have completed the 7 steps. It took me about 11 minutes.

Thanks Dylan! I just sent the invite. Will you let me know here once you've accepted it so I can make sure everything looks the way it should?

I had added the eighth step yesterday and forgot to change it in the instructions about replying. I apologize for not being clear.

**Comment by eldreddyl** [comment]
No problem. I've accepted the invite

**Comment by kbuzard** [comment]
> No problem. I've accepted the invite

Perfect! Thanks @eldreddyl

**Comment by Kellyyyjia** [comment]
I completed all 7 steps, it took 10 minutes.

**Comment by kbuzard** [comment]
> I completed all 7 steps, it took 10 minutes.

Thanks Kelly. I didn't receive your email with your username, but I was able to get it since you posted. I sent you the invitation to join the organization/team. Please reply here when you've accepted it.

**Comment by Kellyyyjia** [comment]
Yes, I saw your invitation. And I have joined the group. Thank you for your help.

Kelly
________________________________

**Comment by kbuzard** [comment]
> Yes, I saw your invitation. And I have joined the group. Thank you for your help. Kelly

Great! Everyone is a member of the repository now, so I'm going to close this issue. It will always be available under the list of closed issues.
