### ISSUE TITLE
Set up Git at the command line

### ISSUE THREAD

**Issue by kbuzard** [kbuzard-SU/GATT-RAs#2]
Deadline: Monday, June 7 at 2pm
1. [Download and install the latest version of Git.](https://git-scm.com/downloads)
2. [Set your username in Git.](https://docs.github.com/en/github/getting-started-with-github/setting-your-username-in-git)
3. [Set your commit email address in Git.](https://docs.github.com/en/articles/setting-your-commit-email-address)
4. Authenticate with Github from Git.
  - When you connect to a GitHub repository from Git, you'll need to authenticate with GitHub using either HTTPS or SSH.
  - Connect over HTTPS (recommended): If you [clone with HTTPS](https://docs.github.com/en/github/getting-started-with-github/about-remote-repositories/#cloning-with-https-urls), you can [cache your GitHub credentials in Git](https://docs.github.com/en/github/getting-started-with-github/caching-your-github-credentials-in-git) using a credential helper.
  - Connecting over SSH: If you [clone with SSH](https://docs.github.com/en/github/getting-started-with-github/about-remote-repositories/#cloning-with-ssh-urls), you must [generate SSH keys](https://docs.github.com/en/github/getting-started-with-github/about-remote-repositories/#cloning-with-ssh-urls) on each computer you use to push or pull from GitHub.

Add a comment here when you have any questions as well as when you have completed all four steps.

**Comment by Kirs10-Riley** [comment]
I am lost on step 4. I tired following the steps for "clone with HTTPS" but every time I try it says failed.

**Comment by kbuzard** [comment]
> I am lost on step 4. I tired following the steps for "clone with HTTPS" but every time I try it says failed.

There are a lot of steps in there. Can you be more specific about at what point it fails? @MatthewRGonzalez may be better at helping to troubleshoot since he's set up his account more recently than I have and the process is different now

**Comment by MatthewRGonzalez** [comment]
> I am lost on step 4. I tired following the steps for "clone with HTTPS" but every time I try it says failed.

Hi @Kirs10-Riley! Can you please provide me with the exact command you used along with the corresponding error message?

**Comment by Kirs10-Riley** [comment]
Hi @MatthewRGonzalez! here is my command and message: 

This 

kirstenriley@Kirstens-MBP ~ % git clone https://github.com/username/repo.git
Cloning into 'repo'...
Username for 'https://github.com': Kirs10-Riley
Password for 'https://Kirs10-Riley@github.com': 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/username/repo.git/'

the username is what I put and the password was the token

**Comment by kbuzard** [comment]
You need to replace https://github.com/username/repo.git

with https://github.com/kbuzard-SU/GATT-RAs

**Comment by Kirs10-Riley** [comment]
Now it is saying there is "no such file or directory"

**Comment by MatthewRGonzalez** [comment]
> Now it is saying there is "no such file or directory"

I can reach out directly to set up a quick zoom call if there’s still a project here. 

Please let me know!

**Comment by kbuzard** [comment]
> You need to replace https://github.com/username/repo.git
> 
> with https://github.com/kbuzard-SU/GATT-RAs

I made a mistake, leaving ".git" off the end. It should be https://github.com/kbuzard-SU/GATT-RAs.git

**Comment by Kirs10-Riley** [comment]
> > Now it is saying there is "no such file or directory"
> 
> I can reach out directly to set up a quick zoom call if there’s still a problem here.
> 
> Please let me know @Kirs10-Riley!

It still says not found. Could we do a quick zoom call? Thanks

**Comment by kbuzard** [comment]
> It still says not found. Could we do a quick zoom call? Thanks

@Kirs10-Riley: I heard from Matt that this was resolved. Let us know if you need any help, and if not, just that you've completed this step.

**Comment by eldreddyl** [comment]
Hello! I've completed all 4 steps and it took me about 25 minutes. For step 4, I cloned using HTTPS.

**Comment by kbuzard** [comment]
> Hello! I've completed all 4 steps and it took me about 25 minutes. For step 4, I cloned using HTTPS.

Perfect! Thanks!

**Comment by Kirs10-Riley** [comment]
I completed all four steps and it took me about 1.5 hours.

**Comment by kbuzard** [comment]
> I completed all four steps and it took me about 1.5 hours.

Thanks @Kirs10-Riley -- especially for sticking with it when the going got rough. I know it's a lot to take in! Now you get to start learning how to do the fun stuff.

**Comment by Kellyyyjia** [comment]
I completed the task around 30 minutes, I cloned with HTTPS also. I did it on Windows System, for IOS it was not working on my side.

**Comment by kbuzard** [comment]
> I completed the task around 30 minutes, I cloned with HTTPS also. I did it on Windows System, for IOS it was not working on my side.

Great! I don't know how the file systems work on macs between the IOS and Windows. You'll need to use Github for managing files. Here's what I'd like to you do: once you've forked the repo in the next step, check to make sure that you can access the files in a way that works for you. Otherwise, we should troubleshoot it to get it set up on the IOS side so you'll be able to do your work easily.

**Comment by Kellyyyjia** [comment]
> > I completed the task around 30 minutes, I cloned with HTTPS also. I did it on Windows System, for IOS it was not working on my side.
> 
> Great! I don't know how the file systems work on macs between the IOS and Windows. You'll need to use Github for managing files. Here's what I'd like to you do: once you've forked the repo in the next step, check to make sure that you can access the files in a way that works for you. Otherwise, we should troubleshoot it to get it set up on the IOS side so you'll be able to do your work easily.

Got it. Thank you
